# Generated by Django 5.2.5 on 2025-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cart_product_alter_cart_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ger',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Farbe (GER)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rang (UZ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=0, max_length=50, verbose_name='Size'),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
