# Generated by Django 5.2.5 on 2025-08-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caryear',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.carmodel'),
        ),
    ]
