# Generated by Django 5.2.5 on 2025-08-28 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_caryear_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carseries",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="core.caryear",
            ),
        ),
    ]
