# Generated by Django 5.2.5 on 2025-08-22 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_color_en_product_color_ger_product_color_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='core.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ger',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung (Ger)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ger',
            field=models.CharField(max_length=50, verbose_name='Produktname (Ger)'),
        ),
    ]
