# Generated by Django 5.2.5 on 2025-08-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_brand_alter_product_description_ger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.ImageField(default='default.png', upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
